"""
Stage 4 Read-Only Monitoring Dashboard Server.

STRICTLY READ-ONLY BY CONSTRUCTION:
  * Only do_GET is implemented. do_POST / do_PUT / do_DELETE / do_PATCH are
    explicitly defined to return 405, so they cannot fall through to any
    inherited handler.
  * No engine, runner or state-writing module is imported. The process has no
    code path that can place a trade, change a parameter or write to the live
    record; it opens files for reading only.
  * Bound to 127.0.0.1 so it is not reachable off the machine.
"""
import http.server
import json
from pathlib import Path
import socketserver
import sys
from typing import Any, Dict, List

PROJECT_ROOT = Path(__file__).resolve().parents[3]
STATIC_DIR = PROJECT_ROOT / "src" / "lab" / "stage4" / "dashboard"
DATA_DIR = PROJECT_ROOT / "data" / "paper_trading"

# Historical reference pillars. Static by definition -- these are completed
# studies, not live series. Regenerated by stage4_runner, read here only.
PILLARS_PATH = DATA_DIR / "reference_pillars.json"


def _read_jsonl(path: Path, limit: int = 0) -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []
    if not path.exists():
        return rows
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                rows.append(json.loads(line))
            except json.JSONDecodeError:
                continue  # never let one torn row break the dashboard
    if limit and len(rows) > limit:
        rows = rows[-limit:]
    return rows


def _read_json(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return default


class DashboardHandler(http.server.SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=str(STATIC_DIR), **kwargs)

    # -- mutation methods are refused outright ------------------------------
    def _reject(self):
        self.send_response(405)
        self.send_header("Allow", "GET, HEAD")
        self.end_headers()
        self.wfile.write(b"This dashboard is read-only.")

    do_POST = _reject
    do_PUT = _reject
    do_DELETE = _reject
    do_PATCH = _reject

    def log_message(self, fmt, *args):
        pass  # keep the console clean for the daemon

    def do_GET(self):
        routes = {
            "/api/live_state": self._live_state,
            "/api/trade_log": self._trade_log,
            "/api/nav_history": self._nav_history,
            "/api/baselines": self._baselines,
            "/api/gap_events": self._gap_events,
            "/api/feed_health": self._feed_health,
            "/api/pillars": self._pillars,
            "/api/overview": self._overview,
        }
        handler = routes.get(self.path.split("?")[0])
        if handler:
            self._serve_json(handler())
        else:
            super().do_GET()

    def _serve_json(self, data: Any):
        body = json.dumps(data, default=str).encode("utf-8")
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        self.wfile.write(body)

    # -- data sources -------------------------------------------------------

    def _live_state(self) -> Dict[str, Any]:
        return _read_json(DATA_DIR / "live_state.json", {"status": "NO_LIVE_STATE"})

    def _trade_log(self) -> List[Dict[str, Any]]:
        return list(reversed(_read_jsonl(DATA_DIR / "trade_log.jsonl")))

    def _nav_history(self) -> List[Dict[str, Any]]:
        return _read_jsonl(DATA_DIR / "nav_history.jsonl")

    def _baselines(self) -> Dict[str, Any]:
        raw = _read_json(DATA_DIR / "live_baselines_state.json", {})
        if not raw:
            return {"status": "NOT_STARTED", "baselines": {}}
        out: Dict[str, Any] = {}
        initial = raw.get("initial_capital_usd", 1000.0)
        for name, b in raw.get("books", {}).items():
            rets = b.get("net_returns", [])
            if len(rets) >= 2:
                import statistics
                mu = statistics.fmean(rets)
                sd = statistics.pstdev(rets) or 1e-12
                sharpe = (8760 ** 0.5) * (mu / sd)
                cagr = mu * 8760
            else:
                sharpe = cagr = 0.0
            out[name] = {
                "net_sharpe": round(sharpe, 4),
                "cagr_net": round(cagr, 4),
                "max_drawdown": round(b.get("max_drawdown", 0.0), 4),
                "ending_nav_usd": round(b.get("nav", initial), 2),
                "total_pnl_usd": round(b.get("nav", initial) - initial, 2),
                "total_trades": b.get("total_trades", 0),
                "bars_tracked": len(rets),
            }
        return {
            "status": "LIVE",
            "anchor_timestamp_utc": raw.get("anchor_timestamp_utc"),
            "last_processed_timestamp_utc": raw.get("last_processed_timestamp_utc"),
            "initial_capital_usd": initial,
            "baselines": out,
        }

    def _gap_events(self) -> List[Dict[str, Any]]:
        return list(reversed(_read_jsonl(DATA_DIR / "gap_events.jsonl")))

    def _feed_health(self) -> Dict[str, Any]:
        return _read_json(DATA_DIR / "feed_health.json", {"status": "UNKNOWN", "detail": "no health file yet"})

    def _pillars(self) -> Dict[str, Any]:
        return _read_json(PILLARS_PATH, {})

    def _overview(self) -> Dict[str, Any]:
        """Everything the header needs, in one round trip."""
        state = self._live_state()
        health = self._feed_health()
        nav = _read_jsonl(DATA_DIR / "nav_history.jsonl")
        gaps = _read_jsonl(DATA_DIR / "gap_events.jsonl")
        return {
            "live_state": state,
            "feed_health": health,
            "bars_processed": len(nav),
            "first_bar_utc": nav[0]["timestamp_utc"] if nav else None,
            "last_bar_utc": nav[-1]["timestamp_utc"] if nav else None,
            "gap_event_count": len([g for g in gaps if "GAP" in g.get("event_type", "")]),
            "unreachable_event_count": len(
                [g for g in gaps if "UNREACHABLE" in g.get("event_type", "")]
            ),
        }


def run_dashboard_server(port: int = 8888):
    STATIC_DIR.mkdir(parents=True, exist_ok=True)
    server = None
    chosen = port
    for p in range(port, port + 20):
        try:
            server = socketserver.TCPServer(("127.0.0.1", p), DashboardHandler)
            chosen = p
            break
        except OSError:
            continue
    if server is None:
        raise RuntimeError("No available port found for dashboard server.")
    with server as httpd:
        print("=" * 78)
        print("STAGE 4 MONITORING DASHBOARD — READ ONLY")
        print(f"URL: http://127.0.0.1:{chosen}")
        print(f"Reading from: {DATA_DIR}")
        print("Mutation methods (POST/PUT/DELETE/PATCH) return 405 by construction.")
        print("=" * 78)
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            print("\nDashboard server stopped.")


if __name__ == "__main__":
    run_dashboard_server(port=int(sys.argv[1]) if len(sys.argv) > 1 else 8888)
